apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-config
data:
  valkey.conf: |
    protected-mode no
    port 6379
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
spec:
  type: NodePort
  selector:
    app: valkey
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30001 # Matches the containerPort in kind-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
spec:
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:8.0
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/valkey
      volumes:
        - name: config
          configMap:
            name: valkey-config